### ISSUE TITLE
Engine not com,[pilling

### ISSUE THREAD

**Issue by vivvianp1l** [CrusherNotDrip/NeonCrusher-Engine#1]
Heyo, I tried to compile the engine as of recently and currently it's giving me this error
![image](https://user-images.githubusercontent.com/130424149/233214794-20c47ff9-feae-45e2-ad11-3aa322e05baf.png)
Yea, I was trying to compile the engine because I see no releases as of now in this repository, so do you mind helping me?

**Comment by vivvianp1l** [comment]
Nvm, solved it myself.

**Comment by CrusherNotDrip** [comment]
la stupid
